config/routes.rb
LoLFantasy::Application.routes.draw do
  resources :player_scores

  resources :team_scores

  resources :games

  resources :pro_teams

  resources :players

  resources :waiver_claims

  resources :free_agents

  resources :matches

  resources :teams

  resources :leagues

  resources :users

  resources :globals

  root 'globals#index'

  get 'login' => 'sessions#new'
  post 'sessions' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'register' => 'users#new'

  get 'my_leagues' => 'users#leagues'

  get 'leagues/:id/scoreboard' => 'leagues#scoreboard', as: :scoreboard
  get 'leagues/:id/standings' => 'leagues#standings', as: :standings

  

end

app/models/free_agent.rb
class FreeAgent < ActiveRecord::Base
  belongs_to :league
  has_and_belongs_to_many :players
end

app/models/game.rb
class Game < ActiveRecord::Base
  has_one :team_score1, :class_name => 'TeamScore'
  has_one :team_score2, :class_name => 'TeamScore'
end

app/models/global.rb
class Global < ActiveRecord::Base
end

app/models/league.rb
class League < ActiveRecord::Base
  belongs_to :commissioner, :class_name => 'User'
  has_many :teams
  has_many :matches
end

app/models/match.rb
class Match < ActiveRecord::Base
  belongs_to :league
  belongs_to :team1, :class_name => 'Team'
  belongs_to :team2, :class_name => 'Team'
  belongs_to :winner, :class_name => 'Team'
  belongs_to :loser, :class_name => 'Team'
end

app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :pro_team
  has_many :player_scores
  has_and_belongs_to_many :free_agents
end

app/models/player_score.rb
class PlayerScore < ActiveRecord::Base
  belongs_to :team_score
  belongs_to :player
end

app/models/pro_team.rb
class ProTeam < ActiveRecord::Base
  has_many :players
  has_many :games
end

app/models/team.rb
class Team < ActiveRecord::Base
  belongs_to :owner, :class_name => 'User'
  belongs_to :league
  belongs_to :starting_top, :class_name => 'Player'
  belongs_to :starting_jungle, :class_name => 'Player'
  belongs_to :starting_mid, :class_name => 'Player'
  belongs_to :starting_ad_carry, :class_name => 'Player'
  belongs_to :starting_support, :class_name => 'Player'
  has_many :bench_players, :class_name => 'Player'
  has_many :waiver_claims
end

app/models/team_score.rb
class TeamScore < ActiveRecord::Base
  belongs_to :pro_team
  belongs_to :game
  has_one :player_score_top, :class_name => 'PlayerScore'
  has_one :player_score_jungle, :class_name => 'PlayerScore'
  has_one :player_score_mid, :class_name => 'PlayerScore'
  has_one :player_score_ad_carry, :class_name => 'PlayerScore'
  has_one :player_score_support, :class_name => 'PlayerScore'
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :teams
  has_many :leagues

  before_create :create_remember_token

  def self.authenticate(username = "", password = "")
    user = User.find_by_name(username)
    if user && user.password == password
      return user
    else
      return false
    end
  end

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

  def create_remember_token
    self.remember_token = User.encrypt(User.new_remember_token)
  end
end

app/models/waiver_claim.rb
class WaiverClaim < ActiveRecord::Base
  belongs_to :player
  belongs_to :dropping_player, :class_name => 'Player'
  belongs_to :team
end

app/controllers/waiver_claims_controller.rb
class WaiverClaimsController < ApplicationController
  before_action :set_waiver_claim, only: [:show, :edit, :update, :destroy]

  # GET /waiver_claims
  # GET /waiver_claims.json
  def index
    @waiver_claims = WaiverClaim.all
  end

  # GET /waiver_claims/1
  # GET /waiver_claims/1.json
  def show
  end

  # GET /waiver_claims/new
  def new
    @waiver_claim = WaiverClaim.new
  end

  # GET /waiver_claims/1/edit
  def edit
  end

  # POST /waiver_claims
  # POST /waiver_claims.json
  def create
    @waiver_claim = WaiverClaim.new(waiver_claim_params)

    respond_to do |format|
      if @waiver_claim.save
        format.html { redirect_to @waiver_claim, notice: 'Waiver claim was successfully created.' }
        format.json { render action: 'show', status: :created, location: @waiver_claim }
      else
        format.html { render action: 'new' }
        format.json { render json: @waiver_claim.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /waiver_claims/1
  # PATCH/PUT /waiver_claims/1.json
  def update
    respond_to do |format|
      if @waiver_claim.update(waiver_claim_params)
        format.html { redirect_to @waiver_claim, notice: 'Waiver claim was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @waiver_claim.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /waiver_claims/1
  # DELETE /waiver_claims/1.json
  def destroy
    @waiver_claim.destroy
    respond_to do |format|
      format.html { redirect_to waiver_claims_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_waiver_claim
      @waiver_claim = WaiverClaim.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def waiver_claim_params
      params.require(:waiver_claim).permit(:player_id, :team_id)
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/globals_helper.rb
module GlobalsHelper
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/pro_teams_helper.rb
module ProTeamsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def log_out
    cookies.delete :remember_token
    current_user = nil
  end

  def logged_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  private

  def user_from_remember_token
    User.authenticate_with_salt(*remember_token)
  end

  def remember_token
    cookies.signed[:remember_token] || [nil, nil]
  end

end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/waiver_claims_helper.rb
module WaiverClaimsHelper
end

app/views/waiver_claims/_form.html.erb
<%= form_for(@waiver_claim) do |f| %>
  <% if @waiver_claim.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@waiver_claim.errors.count, "error") %> prohibited this waiver_claim from being saved:</h2>

      <ul>
      <% @waiver_claim.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :player_id %><br>
    <%= f.number_field :player_id %>
  </div>
  <div class="field">
    <%= f.label :team_id %><br>
    <%= f.number_field :team_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/waiver_claims/edit.html.erb
<h1>Editing waiver_claim</h1>

<%= render 'form' %>

<%= link_to 'Show', @waiver_claim %> |
<%= link_to 'Back', waiver_claims_path %>

app/views/waiver_claims/index.html.erb
<h1>Listing waiver_claims</h1>

<table>
  <thead>
    <tr>
      <th>Team</th>
      <th>Player</th>
      <th>Dropping Player</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @waiver_claims.each do |waiver_claim| %>
      <tr>
        <td><%= link_to "#{waiver_claim.team.league.name}: #{waiver_claim.team.name}", waiver_claim.team %></td>
        <td><%= link_to "#{waiver_claim.player.pro_team.handle} #{waiver_claim.player.name}", waiver_claim.player %></td>
        <td><%= link_to "#{waiver_claim.dropping_player.pro_team.handle} #{waiver_claim.dropping_player.name}", waiver_claim.dropping_player %></td>
        <td><%= link_to 'Show', waiver_claim %></td>
        <td><%= link_to 'Edit', edit_waiver_claim_path(waiver_claim) %></td>
        <td><%= link_to 'Destroy', waiver_claim, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Waiver claim', new_waiver_claim_path %>

app/views/waiver_claims/new.html.erb
<h1>New waiver_claim</h1>

<%= render 'form' %>

<%= link_to 'Back', waiver_claims_path %>

app/views/waiver_claims/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Player:</strong>
  <%= @waiver_claim.player_id %>
</p>

<p>
  <strong>Team:</strong>
  <%= @waiver_claim.team_id %>
</p>

<%= link_to 'Edit', edit_waiver_claim_path(@waiver_claim) %> |
<%= link_to 'Back', waiver_claims_path %>