config/routes.rb
LoLFantasy::Application.routes.draw do
  resources :player_scores

  resources :team_scores

  resources :games

  resources :pro_teams

  resources :players

  resources :waiver_claims

  resources :free_agents

  resources :matches

  resources :teams

  resources :leagues

  resources :users

  resources :globals

  root 'globals#index'

  get 'login' => 'sessions#new'
  post 'sessions' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'register' => 'users#new'

  get 'my_leagues' => 'users#leagues'

  get 'leagues/:id/scoreboard' => 'leagues#scoreboard', as: :scoreboard
  get 'leagues/:id/standings' => 'leagues#standings', as: :standings

  

end

app/models/free_agent.rb
class FreeAgent < ActiveRecord::Base
  belongs_to :league
  has_and_belongs_to_many :players
end

app/models/game.rb
class Game < ActiveRecord::Base
  has_one :team_score1, :class_name => 'TeamScore'
  has_one :team_score2, :class_name => 'TeamScore'
end

app/models/global.rb
class Global < ActiveRecord::Base
end

app/models/league.rb
class League < ActiveRecord::Base
  belongs_to :commissioner, :class_name => 'User'
  has_many :teams
  has_many :matches
end

app/models/match.rb
class Match < ActiveRecord::Base
  belongs_to :league
  belongs_to :team1, :class_name => 'Team'
  belongs_to :team2, :class_name => 'Team'
  belongs_to :winner, :class_name => 'Team'
  belongs_to :loser, :class_name => 'Team'
end

app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :pro_team
  has_many :player_scores
  has_and_belongs_to_many :free_agents
end

app/models/player_score.rb
class PlayerScore < ActiveRecord::Base
  belongs_to :team_score
  belongs_to :player
end

app/models/pro_team.rb
class ProTeam < ActiveRecord::Base
  has_many :players
  has_many :games
end

app/models/team.rb
class Team < ActiveRecord::Base
  belongs_to :owner, :class_name => 'User'
  belongs_to :league
  belongs_to :starting_top, :class_name => 'Player'
  belongs_to :starting_jungle, :class_name => 'Player'
  belongs_to :starting_mid, :class_name => 'Player'
  belongs_to :starting_ad_carry, :class_name => 'Player'
  belongs_to :starting_support, :class_name => 'Player'
  has_many :bench_players, :class_name => 'Player'
  has_many :waiver_claims
end

app/models/team_score.rb
class TeamScore < ActiveRecord::Base
  belongs_to :pro_team
  belongs_to :game
  has_one :player_score_top, :class_name => 'PlayerScore'
  has_one :player_score_jungle, :class_name => 'PlayerScore'
  has_one :player_score_mid, :class_name => 'PlayerScore'
  has_one :player_score_ad_carry, :class_name => 'PlayerScore'
  has_one :player_score_support, :class_name => 'PlayerScore'
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :teams
  has_many :leagues

  before_create :create_remember_token

  def self.authenticate(username = "", password = "")
    user = User.find_by_name(username)
    if user && user.password == password
      return user
    else
      return false
    end
  end

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

  def create_remember_token
    self.remember_token = User.encrypt(User.new_remember_token)
  end
end

app/models/waiver_claim.rb
class WaiverClaim < ActiveRecord::Base
  belongs_to :player
  belongs_to :dropping_player, :class_name => 'Player'
  belongs_to :team
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  before_action :set_league, only: [:show, :edit, :update, :destroy]

  # GET /leagues
  # GET /leagues.json
  def index
    @leagues = League.all
  end

  # GET /leagues/1
  # GET /leagues/1.json
  def show
  end

  # GET /leagues/new
  def new
    @league = League.new
  end

  # GET /leagues/1/edit
  def edit
  end

  # POST /leagues
  # POST /leagues.json
  def create
    @league = League.new(league_params)

    respond_to do |format|
      if @league.save
        format.html { redirect_to @league, notice: 'League was successfully created.' }
        format.json { render action: 'show', status: :created, location: @league }
      else
        format.html { render action: 'new' }
        format.json { render json: @league.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /leagues/1
  # PATCH/PUT /leagues/1.json
  def update
    respond_to do |format|
      if @league.update(league_params)
        format.html { redirect_to @league, notice: 'League was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @league.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leagues/1
  # DELETE /leagues/1.json
  def destroy
    @league.destroy
    respond_to do |format|
      format.html { redirect_to leagues_url }
      format.json { head :no_content }
    end
  end

  # GET /leagues/1/scoreboard
  def scoreboard
    @league = League.find(params[:id])
    @matches = Match.where('league_id = ? AND week = ?', params[:id], Global.first.current_week)
  end

  # GET /leagues/1/standings
  def standings
    @league = League.find(params[:id])
    @matches = Match.where('league_id = ?', params[:id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_league
      @league = League.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def league_params
      params.require(:league).permit(:private, :password, :commissioner_id, :type, :killPoints, :deathPoints, :assistPoints, :minionKills, :gameLength, :maxTeams)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/globals_helper.rb
module GlobalsHelper
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/pro_teams_helper.rb
module ProTeamsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def log_out
    cookies.delete :remember_token
    current_user = nil
  end

  def logged_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  private

  def user_from_remember_token
    User.authenticate_with_salt(*remember_token)
  end

  def remember_token
    cookies.signed[:remember_token] || [nil, nil]
  end

end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/leagues/_form.html.erb
<%= form_for(@league) do |f| %>
  <% if @league.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@league.errors.count, "error") %> prohibited this league from being saved:</h2>

      <ul>
      <% @league.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :private %><br>
    <%= f.check_box :private %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :commissioner_id %><br>
    <%= f.number_field :commissioner_id %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :killPoints %><br>
    <%= f.number_field :killPoints %>
  </div>
  <div class="field">
    <%= f.label :deathPoints %><br>
    <%= f.number_field :deathPoints %>
  </div>
  <div class="field">
    <%= f.label :assistPoints %><br>
    <%= f.number_field :assistPoints %>
  </div>
  <div class="field">
    <%= f.label :minionKills %><br>
    <%= f.number_field :minionKills %>
  </div>
  <div class="field">
    <%= f.label :gameLength %><br>
    <%= f.number_field :gameLength %>
  </div>
  <div class="field">
    <%= f.label :maxTeams %><br>
    <%= f.number_field :maxTeams %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/leagues/edit.html.erb
<h1>Editing league</h1>

<%= render 'form' %>

<%= link_to 'Show', @league %> |
<%= link_to 'Back', leagues_path %>

app/views/leagues/index.html.erb
<h1>Listing leagues</h1>

<ul>
    <li><%= link_to 'Home', root_path %></li>
    <li><%= link_to 'Leagues', leagues_path %></li>
    <% if logged_in? %>
        <li><%= link_to 'My Leagues', my_leagues_path %></li>
    <% end %>
</ul>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Private</th>
      <th>Password</th>
      <th>Commissioner</th>
      <th>League Type</th>
      <th>Kill Points</th>
      <th>Death Points</th>
      <th>Assist Points</th>
      <th>Minion Kills Carry</th>
      <th>Minion Kills Support</th>
      <th>Game Normal</th>
      <th>Max Teams</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @leagues.each do |league| %>
      <tr>
        <td><%= league.name %></td>
        <td><%= league.private %></td>
        <td><%= league.password %></td>
        <td><%= link_to league.commissioner.name, league.commissioner %></td>
        <td><%= league.league_type %></td>
        <td><%= league.kill_points %></td>
        <td><%= league.death_points %></td>
        <td><%= league.assist_points %></td>
        <td><%= league.minion_kills_carry %></td>
        <td><%= league.minion_kills_support %></td>
        <td><%= league.game_normal %></td>
        <td><%= league.max_teams %></td>
        <td><%= link_to 'Show', league %></td>
        <td><%= link_to 'Edit', edit_league_path(league) %></td>
        <td><%= link_to 'Destroy', league, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New League', new_league_path %>

app/views/leagues/new.html.erb
<h1>New league</h1>

<%= render 'form' %>

<%= link_to 'Back', leagues_path %>

app/views/leagues/scoreboard.html.erb
<h1>Scoreboard</h1>

<ul>
    <li><%= link_to 'Home', root_path %></li>
    <li><%= link_to 'League Home', @league %></li>
    <li><%= link_to 'Standings', standings_path %></li>
    <li><%= link_to 'Scoreboard', scoreboard_path %></li>
    <li><%= link_to 'Free Agents', free_agent_path %></li>
    <% if logged_in? %>
        <li><%= link_to 'My Team', @league %></li>
    <% end %>
</ul>

<table>
    <thead>
    <tr>
        <th>League</th>
        <th>Season</th>
        <th>Split</th>
        <th>Week</th>
        <th>Team1 Score</th>
        <th>Team2 Score</th>
        <th>Team 1</th>
        <th>Team 2</th>
        <th>Winner</th>
        <th>Loser</th>
    </tr>
    </thead>

    <tbody>
    <% @matches.each do |match| %>
        <tr>
            <td><%= match.league_id %></td>
            <td><%= match.season %></td>
            <td><%= match.split %></td>
            <td><%= match.week %></td>
            <td><%= match.team1_score %></td>
            <td><%= match.team2_score %></td>
            <td><%= match.team1.name %></td>
            <td><%= match.team2.name %></td>
            <td><%= match.winner.name %></td>
            <td><%= match.loser.name %></td>
        </tr>
    <% end %>
    </tbody>
</table>

app/views/leagues/show.html.erb
<p id="notice"><%= notice %></p>

<ul>
    <li><%= link_to 'Home', root_path %></li>
    <li><%= link_to 'League Home', @league %></li>
    <li><%= link_to 'Standings', standings_path %></li>
    <li><%= link_to 'Scoreboard', scoreboard_path %></li>
    <li><%= link_to 'Free Agents', free_agent_path %></li>
    <% if logged_in? %>
        <li><%= link_to 'My Team', @league %></li>
    <% end %>
</ul>

<p>
    <strong>Name:</strong>
    <%= @league.name %>
</p>

<p>
  <strong>Private:</strong>
  <%= @league.private %>
</p>

<p>
  <strong>Password:</strong>
  <%= @league.password %>
</p>

<p>
  <strong>Commissioner:</strong>
  <%= link_to @league.commissioner.name, @league.commissioner %>
</p>

<p>
  <strong>League Type:</strong>
  <%= @league.league_type %>
</p>

<p>
  <strong>Kill Points:</strong>
  <%= @league.kill_points %>
</p>

<p>
  <strong>Death Points:</strong>
  <%= @league.death_points %>
</p>

<p>
  <strong>Assist Points:</strong>
  <%= @league.assist_points %>
</p>

<p>
  <strong>Minion Kills Carry:</strong>
  <%= @league.minion_kills_carry %>
</p>

<p>
    <strong>Minion Kills Support:</strong>
    <%= @league.minion_kills_support %>
</p>

<p>
  <strong>Game Normal:</strong>
  <%= @league.game_normal %>
</p>

<p>
  <strong>Max Teams:</strong>
  <%= @league.max_teams %>
</p>

<%= link_to 'Edit', edit_league_path(@league) %> |
<%= link_to 'Back', leagues_path %>

app/views/leagues/standings.html.erb
<h1>Standings</h1>

<ul>
    <li><%= link_to 'Home', root_path %></li>
    <li><%= link_to 'League Home', @league %></li>
    <li><%= link_to 'Standings', standings_path %></li>
    <li><%= link_to 'Scoreboard', scoreboard_path %></li>
    <li><%= link_to 'Free Agents', free_agent_path %></li>
    <% if logged_in? %>
        <li><%= link_to 'My Team', @league %></li>
    <% end %>
</ul>