config/routes.rb
LoLFantasy::Application.routes.draw do
  resources :player_scores

  resources :team_scores

  resources :games

  resources :pro_teams

  resources :players

  resources :waiver_claims

  resources :free_agents

  resources :matches

  resources :teams

  resources :leagues

  resources :users

  resources :globals

  root 'globals#index'

  get 'login' => 'sessions#new'
  post 'sessions' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'register' => 'users#new'

  get 'my_leagues' => 'users#leagues'

  get 'leagues/:id/scoreboard' => 'leagues#scoreboard', as: :scoreboard
  get 'leagues/:id/standings' => 'leagues#standings', as: :standings

  

end

app/models/free_agent.rb
class FreeAgent < ActiveRecord::Base
  belongs_to :league
  has_and_belongs_to_many :players
end

app/models/game.rb
class Game < ActiveRecord::Base
  has_one :team_score1, :class_name => 'TeamScore'
  has_one :team_score2, :class_name => 'TeamScore'
end

app/models/global.rb
class Global < ActiveRecord::Base
end

app/models/league.rb
class League < ActiveRecord::Base
  belongs_to :commissioner, :class_name => 'User'
  has_many :teams
  has_many :matches
end

app/models/match.rb
class Match < ActiveRecord::Base
  belongs_to :league
  belongs_to :team1, :class_name => 'Team'
  belongs_to :team2, :class_name => 'Team'
  belongs_to :winner, :class_name => 'Team'
  belongs_to :loser, :class_name => 'Team'
end

app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :pro_team
  has_many :player_scores
  has_and_belongs_to_many :free_agents
end

app/models/player_score.rb
class PlayerScore < ActiveRecord::Base
  belongs_to :team_score
  belongs_to :player
end

app/models/pro_team.rb
class ProTeam < ActiveRecord::Base
  has_many :players
  has_many :games
end

app/models/team.rb
class Team < ActiveRecord::Base
  belongs_to :owner, :class_name => 'User'
  belongs_to :league
  belongs_to :starting_top, :class_name => 'Player'
  belongs_to :starting_jungle, :class_name => 'Player'
  belongs_to :starting_mid, :class_name => 'Player'
  belongs_to :starting_ad_carry, :class_name => 'Player'
  belongs_to :starting_support, :class_name => 'Player'
  has_many :bench_players, :class_name => 'Player'
  has_many :waiver_claims
end

app/models/team_score.rb
class TeamScore < ActiveRecord::Base
  belongs_to :pro_team
  belongs_to :game
  has_one :player_score_top, :class_name => 'PlayerScore'
  has_one :player_score_jungle, :class_name => 'PlayerScore'
  has_one :player_score_mid, :class_name => 'PlayerScore'
  has_one :player_score_ad_carry, :class_name => 'PlayerScore'
  has_one :player_score_support, :class_name => 'PlayerScore'
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :teams
  has_many :leagues

  before_create :create_remember_token

  def self.authenticate(username = "", password = "")
    user = User.find_by_name(username)
    if user && user.password == password
      return user
    else
      return false
    end
  end

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

  def create_remember_token
    self.remember_token = User.encrypt(User.new_remember_token)
  end
end

app/models/waiver_claim.rb
class WaiverClaim < ActiveRecord::Base
  belongs_to :player
  belongs_to :dropping_player, :class_name => 'Player'
  belongs_to :team
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  # GET /users/leagues
  def leagues
    @teams = Team.where('owner_id = ?', current_user.id)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/globals_helper.rb
module GlobalsHelper
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/pro_teams_helper.rb
module ProTeamsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def log_out
    cookies.delete :remember_token
    current_user = nil
  end

  def logged_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  private

  def user_from_remember_token
    User.authenticate_with_salt(*remember_token)
  end

  def remember_token
    cookies.signed[:remember_token] || [nil, nil]
  end

end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
</div>
<div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Password</th>
      <th>Email</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.password %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/leagues.html.erb
<h1>My Leagues</h1>

<ul>
    <li><%= link_to 'Home', root_path %></li>
    <li><%= link_to 'Leagues', leagues_path %></li>
    <% if logged_in? %>
        <li><%= link_to 'My Leagues', my_leagues_path %></li>
    <% end %>
</ul>

<table>
    <thead>
    <tr>
        <th>League</th>
        <th>Team</th>
    </tr>
    </thead>

    <tbody>
    <% @teams.each do |team| %>
        <tr>
            <td><%= link_to team.league.name, team.league %></td>
            <td><%= link_to team.name, team %></td>
        </tr>
    <% end %>
    </tbody>
</table>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>