config/routes.rb
LoLFantasy::Application.routes.draw do
  resources :player_scores

  resources :team_scores

  resources :games

  resources :pro_teams

  resources :players

  resources :waiver_claims

  resources :free_agents

  resources :matches

  resources :teams

  resources :leagues

  resources :users

  resources :globals

  root 'globals#index'

  get 'login' => 'sessions#new'
  post 'sessions' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'register' => 'users#new'

  get 'my_leagues' => 'users#leagues'

  get 'leagues/:id/scoreboard' => 'leagues#scoreboard', as: :scoreboard
  get 'leagues/:id/standings' => 'leagues#standings', as: :standings

  

end

app/models/free_agent.rb
class FreeAgent < ActiveRecord::Base
  belongs_to :league
  has_and_belongs_to_many :players
end

app/models/game.rb
class Game < ActiveRecord::Base
  has_one :team_score1, :class_name => 'TeamScore'
  has_one :team_score2, :class_name => 'TeamScore'
end

app/models/global.rb
class Global < ActiveRecord::Base
end

app/models/league.rb
class League < ActiveRecord::Base
  belongs_to :commissioner, :class_name => 'User'
  has_many :teams
  has_many :matches
end

app/models/match.rb
class Match < ActiveRecord::Base
  belongs_to :league
  belongs_to :team1, :class_name => 'Team'
  belongs_to :team2, :class_name => 'Team'
  belongs_to :winner, :class_name => 'Team'
  belongs_to :loser, :class_name => 'Team'
end

app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :pro_team
  has_many :player_scores
  has_and_belongs_to_many :free_agents
end

app/models/player_score.rb
class PlayerScore < ActiveRecord::Base
  belongs_to :team_score
  belongs_to :player
end

app/models/pro_team.rb
class ProTeam < ActiveRecord::Base
  has_many :players
  has_many :games
end

app/models/team.rb
class Team < ActiveRecord::Base
  belongs_to :owner, :class_name => 'User'
  belongs_to :league
  belongs_to :starting_top, :class_name => 'Player'
  belongs_to :starting_jungle, :class_name => 'Player'
  belongs_to :starting_mid, :class_name => 'Player'
  belongs_to :starting_ad_carry, :class_name => 'Player'
  belongs_to :starting_support, :class_name => 'Player'
  has_many :bench_players, :class_name => 'Player'
  has_many :waiver_claims
end

app/models/team_score.rb
class TeamScore < ActiveRecord::Base
  belongs_to :pro_team
  belongs_to :game
  has_one :player_score_top, :class_name => 'PlayerScore'
  has_one :player_score_jungle, :class_name => 'PlayerScore'
  has_one :player_score_mid, :class_name => 'PlayerScore'
  has_one :player_score_ad_carry, :class_name => 'PlayerScore'
  has_one :player_score_support, :class_name => 'PlayerScore'
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :teams
  has_many :leagues

  before_create :create_remember_token

  def self.authenticate(username = "", password = "")
    user = User.find_by_name(username)
    if user && user.password == password
      return user
    else
      return false
    end
  end

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

  def create_remember_token
    self.remember_token = User.encrypt(User.new_remember_token)
  end
end

app/models/waiver_claim.rb
class WaiverClaim < ActiveRecord::Base
  belongs_to :player
  belongs_to :dropping_player, :class_name => 'Player'
  belongs_to :team
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: [:show, :edit, :update, :destroy]

  # GET /matches
  # GET /matches.json
  def index
    @matches = Match.all
  end

  # GET /matches/1
  # GET /matches/1.json
  def show
  end

  # GET /matches/new
  def new
    @match = Match.new
  end

  # GET /matches/1/edit
  def edit
  end

  # POST /matches
  # POST /matches.json
  def create
    @match = Match.new(match_params)

    respond_to do |format|
      if @match.save
        format.html { redirect_to @match, notice: 'Match was successfully created.' }
        format.json { render action: 'show', status: :created, location: @match }
      else
        format.html { render action: 'new' }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matches/1
  # PATCH/PUT /matches/1.json
  def update
    respond_to do |format|
      if @match.update(match_params)
        format.html { redirect_to @match, notice: 'Match was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1
  # DELETE /matches/1.json
  def destroy
    @match.destroy
    respond_to do |format|
      format.html { redirect_to matches_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
      @match = Match.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def match_params
      params.require(:match).permit(:league_id, :week, :season, :split, :team1_id, :team2_id, :team1Score, :team2Score, :winner_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/globals_helper.rb
module GlobalsHelper
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/pro_teams_helper.rb
module ProTeamsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def log_out
    cookies.delete :remember_token
    current_user = nil
  end

  def logged_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  private

  def user_from_remember_token
    User.authenticate_with_salt(*remember_token)
  end

  def remember_token
    cookies.signed[:remember_token] || [nil, nil]
  end

end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/matches/_form.html.erb
<%= form_for(@match) do |f| %>
  <% if @match.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
      <% @match.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :league_id %><br>
    <%= f.number_field :league_id %>
  </div>
  <div class="field">
    <%= f.label :week %><br>
    <%= f.number_field :week %>
  </div>
  <div class="field">
    <%= f.label :season %><br>
    <%= f.number_field :season %>
  </div>
  <div class="field">
    <%= f.label :split %><br>
    <%= f.number_field :split %>
  </div>
  <div class="field">
    <%= f.label :team1_id %><br>
    <%= f.number_field :team1_id %>
  </div>
  <div class="field">
    <%= f.label :team2_id %><br>
    <%= f.number_field :team2_id %>
  </div>
  <div class="field">
    <%= f.label :team1Score %><br>
    <%= f.number_field :team1Score %>
  </div>
  <div class="field">
    <%= f.label :team2Score %><br>
    <%= f.number_field :team2Score %>
  </div>
  <div class="field">
    <%= f.label :winner_id %><br>
    <%= f.number_field :winner_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/matches/edit.html.erb
<h1>Editing match</h1>

<%= render 'form' %>

<%= link_to 'Show', @match %> |
<%= link_to 'Back', matches_path %>

app/views/matches/index.html.erb
<h1>Listing matches</h1>

<table>
  <thead>
    <tr>
      <th>League</th>
      <th>Season</th>
      <th>Split</th>
      <th>Week</th>
      <th>Team1 Score</th>
      <th>Team2 Score</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @matches.each do |match| %>
      <tr>
        <td><%= match.league_id %></td>
        <td><%= match.season %></td>
        <td><%= match.split %></td>
        <td><%= match.week %></td>
        <td><%= match.team1_score %></td>
        <td><%= match.team2_score %></td>
        <td><%= link_to 'Show', match %></td>
        <td><%= link_to 'Edit', edit_match_path(match) %></td>
        <td><%= link_to 'Destroy', match, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Match', new_match_path %>

app/views/matches/new.html.erb
<h1>New match</h1>

<%= render 'form' %>

<%= link_to 'Back', matches_path %>

app/views/matches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>League:</strong>
  <%= @match.league_id %>
</p>

<p>
  <strong>Week:</strong>
  <%= @match.week %>
</p>

<p>
  <strong>Season:</strong>
  <%= @match.season %>
</p>

<p>
  <strong>Split:</strong>
  <%= @match.split %>
</p>

<p>
  <strong>Team1:</strong>
  <%= @match.team1_id %>
</p>

<p>
  <strong>Team2:</strong>
  <%= @match.team2_id %>
</p>

<p>
  <strong>Team1score:</strong>
  <%= @match.team1Score %>
</p>

<p>
  <strong>Team2score:</strong>
  <%= @match.team2Score %>
</p>

<p>
  <strong>Winner:</strong>
  <%= @match.winner_id %>
</p>

<%= link_to 'Edit', edit_match_path(@match) %> |
<%= link_to 'Back', matches_path %>